/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakRouteImport } from './routes/speak'
import { Route as SigsRouteImport } from './routes/sigs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as IndexRouteImport } from './routes/index'

const SpeakRoute = SpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const SigsRoute = SigsRouteImport.update({
  id: '/sigs',
  path: '/sigs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/sigs': typeof SigsRoute
  '/speak': typeof SpeakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/sigs': typeof SigsRoute
  '/speak': typeof SpeakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/sigs': typeof SigsRoute
  '/speak': typeof SpeakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/code-of-conduct' | '/contact' | '/sigs' | '/speak'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/code-of-conduct' | '/contact' | '/sigs' | '/speak'
  id: '__root__' | '/' | '/code-of-conduct' | '/contact' | '/sigs' | '/speak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  ContactRoute: typeof ContactRoute
  SigsRoute: typeof SigsRoute
  SpeakRoute: typeof SpeakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speak': {
      id: '/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof SpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigs': {
      id: '/sigs'
      path: '/sigs'
      fullPath: '/sigs'
      preLoaderRoute: typeof SigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  ContactRoute: ContactRoute,
  SigsRoute: SigsRoute,
  SpeakRoute: SpeakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
